.TH INTERNSCTL 1 "March 2023" "internsctl v0.1.0" "User Commands"
.SH NAME
internsctl \- custom Linux command for operations
.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]
.SH DESCRIPTION
The \fBinternsctl\fR command provides various for performing operations.
.SH OPTIONS
.TP
.BR --help
Display help information.
.TP 
.BR --version
Display the command version.
.TP
.BR --cpu-info
display CPU information:
.SH EXAMPLES
Display CPU information:
.B internsctl --cpu-info
.SH SEE ALSO
.BR man (1)
.SH AUTHOR

Written by RITIKA.
